// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(CommerceDataContext))]
    [Migration("20220324180237_UpdateModelsAndSeedDb")]
    partial class UpdateModelsAndSeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 3, 24, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(4860), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sink into a little slice of heaven. Our modern sofas and sleepers are here to satisfy your seating senses. Available in sumptuous leather, soft velvet and a variety of other fabrics to complete your living room ensemble.",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
                            Name = "Sofas",
                            Slug = "sofas"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 3, 14, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(4920), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Best kitchenware and accessories with functionality and a modern style.",
                            ImageUrl = "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2",
                            Name = "Kitchen",
                            Slug = "kitchen"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 3, 19, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(4940), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whether beautifully upholstered or baring their elegant wood frames to the world, our modern beds are so good-looking you’ll want to leave the lights on.",
                            ImageUrl = "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
                            Name = "Beds",
                            Slug = "beds"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 3, 21, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(4950), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quality lighting that evokes emotion.",
                            ImageUrl = "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f",
                            Name = "Lighting",
                            Slug = "lighting"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 3, 22, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(4960), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Keep home office morale high. Whether you’re conferencing for eight or working at a power desk for one, we’ve got you covered.",
                            ImageUrl = "https://images.unsplash.com/photo-1533090161767-e6ffed986c88",
                            Name = "Office",
                            Slug = "office"
                        });
                });

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 23, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5270), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Perfect for lazy days, Harlow's large proportions and plump cushions make relaxing easy. There's two loose side cushions too – prop them where feels best.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/9/2/8/d/928d311ecc71f85f815d9e0d638d34815b4e333f_SOFHLW001GRY_UK_Harlow_Left_Hand_Facing_Chaise_End_Corner_Sofa_Mountain_Grey_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/9/e/8/29e80347e4bdc078b03e426a5acfcf81939b545f_SOFHLW001GRY_UK_Harlow_Left_Hand_Facing_Chaise_End_Corner_Sofa_Mountain_Grey_ar3_2_LB02_LS.jpg" },
                            IsAvailable = false,
                            Name = "Harlow",
                            Price = 1150m,
                            ProductTypeId = 1,
                            Quantity = 20,
                            Sku = "",
                            Slug = "harlow-left-hand-facing-chaise-end-corner-sofa-mountain-grey",
                            Title = "Left Hand Facing Chaise End Corner Sofa, Mountain Grey"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 22, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5280), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Upholstered in velvet with a charming channelled backrest, Amicie's square frame gives a fresh, contemporary feel to that mid-century influence. This chaise end corner sofa's big enough to spread out – or snuggle up. Amicie's a real showstopper, at a great price, too.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/d/b/1/b/db1b0b971f8838b697e3b00191742cbcb06b5f86_SOFAMI052GRY_UK_Amicie_Right_Hand_Facing_Chaise_End_Corner_Sofa_Dark_Anthracite_Velvet_ar3_2_LB.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/e/4/0/ce400ec4b0e6d88df719e6d19039ad93565a71fb_SOFAMI052GRY_UK_Amicie_Right_Hand_Facing_Chaise_End_Corner_Sofa_Dark_Anthracite_Velvet_ar3_2_LB.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/3/1/2/9/31298ca58f0490775fa8df69f807d2876dbac533_SOFAMI052GRY_UK_Amicie_Right_Hand_Facing_Chaise_End_Corner_Sofa_Dark_Anthracite_Velvet_ar3_2_LB." },
                            IsAvailable = false,
                            Name = "Amicie",
                            Price = 925m,
                            ProductTypeId = 1,
                            Quantity = 6,
                            Sku = "",
                            Slug = "amicie-right-hand-facing-chaise-end-corner-sofa-dark-anthracite-recycled-velvet",
                            Title = "Right Hand Facing Chaise End Corner Sofa, Dark Anthracite Recycled Velvet"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 28, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5290), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nothing says luxury quite like Scott. A sleek silhouette with pulled detail cushions, upholstered in plush velvet – it oozes sophistication. The clean lines nod to mid-century design, and there’s plenty of room to snuggle up.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/4/2/3/b4230880125806c26c488923a5db9543e37f7764_SOFSCT028GRY_UK_Scott_3_Seater_Sofa_Petrol_Cotton_Velvet_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/e/1/9/9/e199d0946b2526606fb80bd7f02bc96a41a09a2f_SOFSCT028GRY_UK_Scott_3_Seater_Sofa_Petrol_Cotton_Velvet_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/4/5/a/d/45ad5b38009354f6b67badeff944dc84b44e79b2_SOFSCT028GRY_UK_Scott_3_Seater_Sofa_Petrol_Cotton_Velvet_ar3_2_LB04_PS.png" },
                            IsAvailable = false,
                            Name = "Scott",
                            Price = 1250m,
                            ProductTypeId = 2,
                            Quantity = 8,
                            Sku = "",
                            Slug = "scott-3-seater-sofa-petrol-cotton-velvet",
                            Title = "3 Seater Sofa,Petrol Cotton Velvet"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 15, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5310), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mogen's got it all – for all spaces. Plush, comfy seating that transforms into an equally comfortable bed for guests. Thick, chunky arms. Loose, soft back cushions. Prepare for arguments over who gets to sleep here.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_1.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/f/9/6/e/f96e3b25b9b191fed8e4ed10e9d7f8b1230fa65c_SOFMOG018GRY_UK_Mogen_3_Seater_Sofa_Bed_Steel_Boucle_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_1.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/0/0/7/2/00725b88c7494e46bf8c02db2cbd77a80710609c_SOFMOG018GRY_UK_Mogen_3_Seater_Sofa_Bed_Steel_Boucle_ar3_2_LB02_LS.jpg" },
                            IsAvailable = false,
                            Name = "Mogen",
                            Price = 679m,
                            ProductTypeId = 2,
                            Quantity = 4,
                            Sku = "",
                            Slug = "mogen-3-seater-sofa-bed-steel-boucle",
                            Title = "3 Seater Sofa Bed, Steel Boucle"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 8, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5320), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trent’s deep seats are as relaxing and comfy as they look. And it comes with bolster cushions, making curling up on this corner sofa a little more tempting. Even better? It’s fitted with loose covers, which means washing's a doddle.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_1.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/a/1/1/ca114fa0135d4418ca99912b8206caebfc5cace6_CHATNT009GRY_UK_Trent_Loose_Cover_Corner_Sofa_Washed_Grey_Cotton_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/a/1/5/ca157ff3a9f63adfa93d791fad2d33f32fde31ce_CHATNT009GRY_UK_Trent_Loose_Cover_Corner_Sofa_Washed_Grey_Cotton_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/d/f/9/bdf96a4da119e0ad8965b38e5d4b5a7b5d9aa4b3_CHATNT009GRY_UK_Trent_Loose_Cover_Corner_Sofa_Washed_Grey_Cotton_ar3_2_LB04_PS.png" },
                            IsAvailable = false,
                            Name = "Trent",
                            Price = 2395m,
                            ProductTypeId = 3,
                            Quantity = 3,
                            Sku = "",
                            Slug = "trent-loose-cover-corner-sofa-washed-grey-cotton-fabric",
                            Title = "Loose Cover Corner Sofa, Washed Grey Cotton Fabric"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 3, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5330), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "What's better than a set of 2 presentation saucepans? Mini versions. And that's where Nicolas Vahé's Kasey comes in. Perfect for serving food from hob to table, they're made from stainless steel with rustic brass handles. Obsessed? So are we.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/9/f/1/5/9f15cc2a7c0d35358ab55bc696e5011c9cc69c25_MWHKAS001SIL_UK_Kasey_S2_Mini_Presentation_Pans_Silver_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/0/4/d/2/04d2c1008335e3fe5dfbfdffe1b7ffeec936fd87_MWHKAS001SIL_UK_Kasey_S2_Mini_Presentation_Pans_Silver_ar3_2_LB04_DT.png" },
                            IsAvailable = false,
                            Name = "Kasey",
                            Price = 55m,
                            ProductTypeId = 4,
                            Quantity = 12,
                            Sku = "",
                            Slug = "kasey-set-of-2-mini-presentation-pans-stainless-steel",
                            Title = "Set of 2 Mini Presentation Pans, Stainless Steel"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 7, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5350), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Colter's industrial tone lets you bring style to every corner of your kitchen. In a navy powder-coated metal, this pedal bin contains two 30L sections, ideal for splitting up your recycling. Doing your bit for the planet, and looking good too.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/7/1/1/5711497d45fea79f142b43abdf4926098f914bf0_BTACOL008NAV_UK_Colter_60L_Soft_Close_Double_Recycling_Pedal_Bin_x2_30L_Midnight_Navy_ar3_2_LB0.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/2/c/c/a2cc4dd61b3506b564bb971ff4e311bd8b91f5ab_BTACOL008NAV_UK_Colter_60L_Soft_Close_Double_Recycling_Pedal_Bin_x2_30L_Midnight_Navy_ar3_2_LB0.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/e/3/b/b/e3bb3af9af172ada3a69910c3072a2ba6981ec80_BTACOL008NAV_UK_Colter_60L_Soft_Close_Double_Recycling_Pedal_Bin_x2_30L_Midnight_Navy_ar3_2_LB0.png" },
                            IsAvailable = false,
                            Name = "Colter",
                            Price = 110m,
                            ProductTypeId = 5,
                            Quantity = 4,
                            Sku = "",
                            Slug = "colter-soft-close-double-recycling-pedal-bin-2-x-30l-midnight-navy",
                            Title = "Soft Close Double Recycling Pedal Bin, 2 x 30L, Midnight Navy"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 12, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5360), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "What's speckled, stoneware and brimming with Nordic style? Bloomingville’s Kendra. We love the organic shape and timeless design of this bottle. Each one is unique which makes it extra special. And there’s more to enjoy from this collection, too.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/a/4/f/ba4f54fdad96e521e4cd66b619741f23c1ad7caa_MWHKEN018GRY_UK_Kendra_Speckle_Oil_Vinegar_Grey_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/3/3/a/5/33a56aac56461615633ff112ddc3758b950d6035_MWHKEN018GRY_UK_Kendra_Speckle_Oil_Vinegar_Grey_ar3_2_LB04_DT.png" },
                            IsAvailable = false,
                            Name = "Kendra",
                            Price = 29m,
                            ProductTypeId = 6,
                            Quantity = 4,
                            Sku = "",
                            Slug = "kendra-oil-vinegar-bottle-grey-speckled-stoneware",
                            Title = "Oil & Vinegar Bottle, Grey Speckled Stoneware"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 17, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5380), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Roscoe's perfect for breathing new life into your bedroom. Clean lines and walnut legs hint at Nordic charm, while the fresh fabric ups the luxe. We designed it with comfort and quality in mind – that's why it's fitted with a padded and upholstered headboard, with sprung birch slats.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/0/5/2/b052fef9dca93969b9ead73cccd754864f45b6a8_BEDROS052BEI_UK_Roscoe_Double_Bed_Salcombe_Beige_Walnut_Stain_Legs_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/0/7/0/0/0700f596f49cca90c8af5b87451950864cb9307a_BEDROS052BEI_UK_Roscoe_Double_Bed_Salcombe_Beige_Walnut_Stain_Legs_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/1/7/b/5/17b523af9e35d9c707e00a3c2cf02dac0a049d58_BEDROS052BEI_UK_Roscoe_Double_Bed_Salcombe_Beige_Walnut_Stain_Legs_ar3_2_LB06_DM.png" },
                            IsAvailable = false,
                            Name = "Roscoe",
                            Price = 495m,
                            ProductTypeId = 7,
                            Quantity = 4,
                            Sku = "",
                            Slug = "roscoe-double-bed-salcombe-beige-dark-stain-oak-legs",
                            Title = "Double Bed, Salcombe Beige & Dark Stain Oak Legs"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 22, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5390), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Traditional design, with a luxury twist. Check out the generous curves, brass legs and welcoming proportions on this bed. Trudy's one to snuggle in to – in style. And did we mention the concealed ottoman storage and recycled fabric?",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/6/2/e/8/62e8d5d5bbbdea0e695c868385ae307a27aac2ac_BEDTRU013GRE_UK_Trudy_Double_Storage_Ottoman_Bed_Fir_Green_Velvet_Brass_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/0/a/7/b/0a7bbbecba1ce2889a69eb6149450520d85043bc_BEDTRU013GRE_UK_Trudy_Double_Storage_Ottoman_Bed_Fir_Green_Velvet_Brass_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/3/f/b/2/3fb262d26a457275c94a7ead3f6d7dfa07e2a58e_BEDTRU013GRE_UK_Trudy_Double_Storage_Ottoman_Bed_Fir_Green_Velvet_Brass_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Trudy",
                            Price = 425m,
                            ProductTypeId = 7,
                            Quantity = 4,
                            Sku = "",
                            Slug = "trudy-double-ottoman-storage-bed-ivy-green-velvet-brass",
                            Title = "Double Ottoman Storage Bed, Ivy Green Velvet & Brass"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 27, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5410), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kano's the perfect place for you to peacefully slumber, relax and dream. Just look at those clean lines and rounded corners. It's inspired by Japanese design – highly sophisticated and beautifully simple, it’ll turn your bedroom into a zen retreat.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/f/d/d/5/fdd558cfab614da3ccddc4bd8b1d396b867eb68e_BEDKAN005PNE_UK_MADE_Essentials_Kano_Single_Bed_Natural_Pine_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/a/5/1/2a518c36e189339f779f8f0f2eeaac2e7fd6cbfb_BEDKAN005PNE_UK_MADE_Essentials_Kano_Single_Bed_Natural_Pine_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/9/f/3/6/9f36abb1d74908fba8534771d893ef9134931d85_BEDKAN005PNE_UK_MADE_Essentials_Kano_Single_Bed_Natural_Pine_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/e/8/0/e/e80e72e4ead98245858bd689c6625ce1f230443a_BEDKAN005PNE_UK_MADE_Essentials_Kano_Single_Bed_Natural_Pine_ar3_2_LB06_DM.png" },
                            IsAvailable = false,
                            Name = "Kano",
                            Price = 215m,
                            ProductTypeId = 8,
                            Quantity = 4,
                            Sku = "",
                            Slug = "kano-platform-single-bed-pine",
                            Title = "Platform Single Bed, Pine"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 4, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5420), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Curved wing headboard, slim brass legs and padded upholstery – Otillia's hitting all the right bedroom notes. This dreamy frame is revival with a modern twist. Back to bed? Sure.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/6/8/2/5682c1342febffe0495de833c42579a3882b68a8_BEDOTT004BLU_UK_Otillia_King_Size_Bed_Dark_Navy_Velvet_Brass_Legs_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/e/8/2/2e823ddf2b44cce4ef6b8f0977e25b4a53642bd4_BEDOTT004BLU_UK_Otillia_King_Size_Bed_Dark_Navy_Velvet_Brass_Legs_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/8/a/6/2/8a62ca13a8042789b609140e122c83202c248b91_BEDOTT004BLU_UK_Otillia_King_Size_Bed_Dark_Navy_Velvet_Brass_Legs_ar3_2_LB06_DM.png" },
                            IsAvailable = false,
                            Name = "Otillia",
                            Price = 595m,
                            ProductTypeId = 9,
                            Quantity = 4,
                            Sku = "",
                            Slug = "otillia-king-size-bed-dark-navy-velvet-brass-legs",
                            Title = "King Size Bed, Dark Navy Velvet with Brass Legs"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 16, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5430), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cosy, Nordic opulence? Ankhara's into it. A refined combination of black stained oak, dark velvet and cane, this bed feels warm and welcoming. It's what dreams are made of.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/9/4/c/594c2e26374846a48fb75ad17c9528942be3b0e0_BEDANK005GRY_UK_Ankhara_King_Size_Bed_Rattan_Black_Stain_Oak_Dark_Anthracite_Velvet_ar3_2_LB02_.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/2/f/a/52fac05ea84a88736c4877d54ad9be00dd4746f1_BEDANK005GRY_UK_Ankhara_King_Size_Bed_Rattan_Black_Stain_Oak_Dark_Anthracite_Velvet_ar3_2_LB01_.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/6/6/e/b66e4239bef8f359654cc689d0fb56745edd86ab_BEDANK005GRY_UK_Ankhara_King_Size_Bed_Rattan_Black_Stain_Oak_Dark_Anthracite_Velvet_ar3_2_LB06_." },
                            IsAvailable = false,
                            Name = "Ankhara",
                            Price = 875m,
                            ProductTypeId = 9,
                            Quantity = 4,
                            Sku = "",
                            Slug = "ankhara-king-size-bed-rattan-black-stain-oak-dark-anthracite-velvet",
                            Title = "King Size Bed, Rattan & Black Stain Oak, Dark Anthracite Velvet"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 2, 28, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5440), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Charley's retro vibes give your bedroom first class design, without the hefty price tag. The buttoned detailing and subtle curved headboard bring personality and style – upholstered in soft hail grey, this king size bed is (almost) too nice to sleep in. And check out the storage underneath.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/d/a/b/f/dabf9e764a4769b9cf36b1dc0c6a3c09928ab1cf_BEDCHL016GRY_UK_Charley_King_Size_Bed_Storage_Hail_Grey_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/f/6/f/1/f6f159c169dc6e84022ab32a550e88e84ff308d3_BEDCHL016GRY_UK_Charley_King_Size_Bed_Storage_Hail_Grey_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/c/9/c/cc9c2f7b966c4bd640b3691e5627780930d6b5be_BEDCHL016GRY_UK_Charley_King_Size_Bed_Storage_Hail_Grey_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/4/0/4/c404791784bd8e24201ef67a84854c9993e66934_BEDCHL016GRY_UK_Charley_King_Size_Bed_Storage_Hail_Grey_ar3_2_LB08_DM.png" },
                            IsAvailable = false,
                            Name = "Charley",
                            Price = 775m,
                            ProductTypeId = 9,
                            Quantity = 8,
                            Sku = "",
                            Slug = "charley-king-size-ottoman-storage-bed-hail-grey",
                            Title = "King Size Ottoman Storage Bed, Hail Grey"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 12, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5460), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Down for a little drama? Hello, Bow. This large overreach floor lamp commands attention – even with the lights off. Matte pink and brass bring a Scandi-glam mix – the soft matte shade takes care of the glow. Adjust the arched stem to light up where you need it.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/0/c/a/4/0ca470e458d628be31c23438487472cc461f0ca6_FLPBOW024PNK_UK_Bow_Large_Arc_Overreach_Floor_Lamp_Pink_Brass_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/f/a/d/b/fadb150fd0e9a4eff4d604476c460082590e0b1e_FLPBOW024PNK_UK_Bow_Large_Arc_Overreach_Floor_Lamp_Pink_Brass_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/6/9/d/7/69d7423f030928e695a2bad25f27976fdddf6d97_FLPBOW024PNK_UK_Bow_Large_Arc_Overreach_Floor_Lamp_Pink_Brass_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Bow",
                            Price = 170m,
                            ProductTypeId = 10,
                            Quantity = 14,
                            Sku = "",
                            Slug = "bow-large-arc-overreach-floor-lamp-pink-brass",
                            Title = "Large Arc Overreach Floor Lamp, Pink & Brass"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 14, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5470), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "From cosy corners to large living spaces, brightening your home with Bree is easy. A classic design with a twist, this tripod floor lamp was designed in our studio",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/1/1/e/a11e9e9c9213fe0518d5a14447d9190c30ea1d1f_FLPBRE002GRN_UK_Bree_Turned_Wood_Tripod_Floor_Lamp_Dark_Wood_Green_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/d/1/c/2/d1c2ab01cfcd099f29af41b47ce47ee69ec19d03_FLPBRE002GRN_UK_Bree_Turned_Wood_Tripod_Floor_Lamp_Dark_Wood_Green_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/1/c/3/0/1c308619a5c2946a047724d4cc3f7d5785eb6e6b_FLPBRE002GRN_UK_Bree_Turned_Wood_Tripod_Floor_Lamp_Dark_Wood_Green_ar3_2_LB03_DT.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/4/b/e/7/4be7dd24371cd3fd143a7b6cfb30c456deefdfbf_FLPBRE002GRN_UK_Bree_Turned_Wood_Tripod_Floor_Lamp_Dark_Wood_Green_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Bree",
                            Price = 185m,
                            ProductTypeId = 10,
                            Quantity = 20,
                            Sku = "",
                            Slug = "bree-turned-wood-tripod-floor-lamp-dark-wood-green",
                            Title = "Turned Wood Tripod Floor Lamp, Dark Wood & Green"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 16, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5480), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bring the romance to your living room with Briz. Check out the rich mix of materials – from the brushed brass base, to the jewel-like textured glass shade. Designed in-house, this plug in wall light's set to leave a glowing impression (literally).",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/9/7/b/9/97b91937c4777d20d2e3c7e43161d0982b1822cc_WLPBRI019GRY_UK_Briz_Plug_in_Wall_Light_Grey_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/1/8/d/b/18db86840e54ff8a8fcc2f346dc142095edf1537_WLPBRI019GRY_UK_Briz_Plug_in_Wall_Light_Grey_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/1/c/b/b1cba7bf27be6298c954588bb32b54e1107ea834_WLPBRI019GRY_UK_Briz_Plug_in_Wall_Light_Grey_ar3_2_LB03_LD.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/1/a/0/5/1a055c9379bd6f9e529b161bfc8f659f1241b3d9_WLPBRI019GRY_UK_Briz_Plug_in_Wall_Light_Grey_ar3_2_LB08_DM.png" },
                            IsAvailable = false,
                            Name = "Briz",
                            Price = 60m,
                            ProductTypeId = 11,
                            Quantity = 6,
                            Sku = "",
                            Slug = "briz-plug-in-wall-light-grey-glass",
                            Title = "Plug In Wall Light, Grey Glass"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 18, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5500), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Task lamps always look really cool and industrial in living spaces. So we’ve taken that style for the Ogilvy Collection. A sleek, practical addition to our Deco Luxe look.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/7/d/a/c/7dac2cb09308746d8ac7639a2e93481cb1e81578_LGTOGL003BLA_UK_Ogilvy_Swing_Arm_Wall_Lamp_Matt_Black_and_Antique_Brass_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/1/1/8/5118aa73a6133dc0c6020dd065786f093aa0814c_LGTOGL003BLA_UK_Ogilvy_Swing_Arm_Wall_Lamp_Matt_Black_and_Antique_Brass_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/7/7/4/b/774ba8914f65dd13e2c4b52b9366ed164ec6e648_LGTOGL003BLA_UK_Ogilvy_Swing_Arm_Wall_Lamp_Matt_Black_and_Antique_Brass_ar3_2_LB06_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/8/3/2/7/8327fb02d0b38c3e8fccdb02f1a47508aa322983_LGTOGL003BLA_UK_Ogilvy_Swing_Arm_Wall_Lamp_Matt_Black_and_Antique_Brass_ar3_2_LB08_DM.png" },
                            IsAvailable = false,
                            Name = "Ogilvy",
                            Price = 70m,
                            ProductTypeId = 11,
                            Quantity = 8,
                            Sku = "",
                            Slug = "ogilvy-swing-arm-wall-lamp-matt-black-and-antique-brass",
                            Title = "Swing Arm Wall Lamp, Matt Black and Antique Brass"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 8, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5510), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sculptural, bold and interesting – that sums up Naila. We created this ceiling light in collaboration with Omayra Maymó, who says it's \"a modern version of a chandelier, using colour and making it more fun and fresher.\" She's won impressive awards for her work, and it's easy to see why. We love the coloured glass and coated metal.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/1/1/9/1/11915617c128c7d84a4d5df35e9e2418e369de5e_CLPNAI001IVO_UK_Naila_Pendant_Ceiling_Light_Burgundy_Ivory_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/4/3/3/f/433ff4aaaf34bce1a0978524bfe2ed4e41329f8f_CLPNAI001IVO_UK_Naila_Pendant_Ceiling_Light_Burgundy_Ivory_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/4/3/4/0/43402b4d2467322b7acaea76713f42a20b55ecdf_CLPNAI001IVO_UK_Naila_Pendant_Ceiling_Light_Burgundy_Ivory_ar3_2_LB06_DM.png" },
                            IsAvailable = false,
                            Name = "Naila",
                            Price = 215m,
                            ProductTypeId = 12,
                            Quantity = 12,
                            Sku = "",
                            Slug = "naila-pendant-ceiling-light-burgundy-and-ivory",
                            Title = "Pendant Ceiling Light, Burgundy & Ivory"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 18, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5530), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create a clean, pared-back look with this Scandi-inspired flush ceiling lamp. Albert's a cool combination of powder-coated metal and wood. The key to a calm, Nordic interior. It's great for bringing style to smaller spaces and lower ceilings.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/0/e/9/a0e937cbd5399428cd9caadfdfbe1af5263e1629_CLPALB028GRY_UK_Albert_Flush_Ceiling_Lamp_Muted_Grey_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/d/0/3/b/d03bc5270b6853df5c5c077708634ee2492bd9cf_CLPALB028GRY_UK_Albert_Flush_Ceiling_Lamp_Muted_Grey_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/3/1/1/a/311a10970051d8a6f2444101376907eb6872d9ff_CLPALB028GRY_UK_Albert_Flush_Ceiling_Lamp_Muted_Grey_ar3_2_LB05_DM.png" },
                            IsAvailable = false,
                            Name = "Albert",
                            Price = 55m,
                            ProductTypeId = 12,
                            Quantity = 8,
                            Sku = "",
                            Slug = "albert-flush-ceiling-lamp-muted-grey",
                            Title = "Flush Ceiling Lamp, Muted Grey"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 8, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5540), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "This is Knox, a sleek, sophisticated office chair that’ll bring a modern aesthetic to your work space. The single seat cushion and supportive back rest sit on top of a sturdy metal frame and wheels. So, even if you’re chained to your desk, it’s easy to move around.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/4/4/e/8/44e8f5598dfd271c66d77e213bc73ce53a381a15_OCHKNX022YEL_UK_Knox_Office_Chair_Mustard_Corduroy_Velvet_with_Black_Legs_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/6/4/e/4/64e4f7830be1b95b6c599883f42914177dfecea4_OCHKNX022YEL_UK_Knox_Office_Chair_Mustard_Corduroy_Velvet_with_Black_Legs_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/b/4/9/7/b49751f01b7139369578f8691e4f6cdb95c6b23b_OCHKNX022YEL_UK_Knox_Office_Chair_Mustard_Corduroy_Velvet_with_Black_Legs_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/9/e/2/c9e2cbf90bf0f9836b806bb999c2cbd8e3e96c54_OCHKNX022YEL_UK_Knox_Office_Chair_Mustard_Corduroy_Velvet_with_Black_Legs_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Knox",
                            Price = 150m,
                            ProductTypeId = 13,
                            Quantity = 5,
                            Sku = "",
                            Slug = "knox-office-chair-mustard-corduroy-velvet-with-black-legs",
                            Title = "Office Chair, Mustard Corduroy Velvet with Black Legs"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 6, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5550), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Forget your standard office chairs, Denham's here to help you work comfortably. It's got a padded seat, arms and backrest, and green fabrication that's easy on the eye. We can't promise it'll help you answer those emails, though.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/8/9/1/c8916f9987b7b6170f106eac7e69f214dca30093_OCHDEN002GRE_UK_Denham_Office_Chair_Darby_Green_Black_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/4/0/a/240aa03ccf035108717b1f30fcc8b225cbb85089_OCHDEN002GRE_UK_Denham_Office_Chair_Darby_Green_Black_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/d/e/5/e/de5ea1df69aa80afef57c41cfebd7673c37a25a2_OCHDEN002GRE_UK_Denham_Office_Chair_Darby_Green_Black_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/e/f/d/2/efd2981e11f2622cd80e5f32d4f4c6b56be8747d_OCHDEN002GRE_UK_Denham_Office_Chair_Darby_Green_Black_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Denham",
                            Price = 250m,
                            ProductTypeId = 13,
                            Quantity = 9,
                            Sku = "",
                            Slug = "denham-office-chair-darby-green-black-leg",
                            Title = "Office Chair, Darby Green & Black Leg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 24, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5560), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Beautiful clean lines, tapered boomerang legs, plenty of storage. Jenson makes your home office work for you. Tim Fenby designed this desk with a Scandinavian-refectory look in mind – and the dark stained oak adds sophistication.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/2/d/a/22da494dc850cb6aef80732bdebe71c6177f8876_DSKJNS074ZDB_UK_Jenson_Desk_Dark_Stain_Oak_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/c/5/8/2/c5820297a109098c2be03489588851963ace9b02_DSKJNS074ZDB_UK_Jenson_Desk_Dark_Stain_Oak_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/a/4/0/e/a40ef4a500f14d13feda9f877bd86d2c18745151_DSKJNS074ZDB_UK_Jenson_Desk_Dark_Stain_Oak_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/3/4/2/a/342a678ff7c6385fd51de828a1e3a83a0401e03c_DSKJNS074ZDB_UK_Jenson_Desk_Dark_Stain_Oak_ar3_2_LB06_DM.png" },
                            IsAvailable = false,
                            Name = "Jenson",
                            Price = 675m,
                            ProductTypeId = 14,
                            Quantity = 4,
                            Sku = "",
                            Slug = "jenson-desk-dark-stain-oak",
                            Title = "Desk, Dark Stain Oak"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 3, 6, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5570), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A design collaboration with SmithMatthias, take your office space to the next level with Leonie. Complete with a cable management feature, 2 handy side drawers, 1 large drawer, and space for your computer up top. Solid oak and oak veneer keep it natural.",
                            Images = new[] { "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/9/6/5/1/965170d0d89bf725fd7a657382cd5423b1517cfc_DSKLEO003ZOK_UK_Leonie_Wide_Desk_Oak_ar3_2_LB01_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/f/8/c/1/f8c1aea53bab3547f5f7f496a9ee2e09cef7f664_DSKLEO003ZOK_UK_Leonie_Wide_Desk_Oak_ar3_2_LB02_LS.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/2/9/0/1/290145d3ff07ceb90483acdf03c50fce2e81d44f_DSKLEO003ZOK_UK_Leonie_Wide_Desk_Oak_ar3_2_LB03_LD.jpg", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/0/a/c/50ac9938f485f4e4955d354a8987b6e36ceca330_DSKLEO003ZOK_UK_Leonie_Wide_Desk_Oak_ar3_2_LB04_PS.png", "https://img.made.com/image/upload/c_pad,d_madeplusgrey.svg,f_auto,w_982,dpr_2.0,q_auto:good,b_rgb:f5f6f4/v4/catalog/product/asset/5/c/0/c/5c0c6c8cfed1103c2be3be796e07e4a5b4c898c9_DSKLEO003ZOK_UK_Leonie_Wide_Desk_Oak_ar3_2_LB07_DM.png" },
                            IsAvailable = false,
                            Name = "Leonie",
                            Price = 450m,
                            ProductTypeId = 14,
                            Quantity = 4,
                            Sku = "",
                            Slug = "leonie-wide-desk-oak",
                            Title = "Wide Desk, Oak"
                        });
                });

            modelBuilder.Entity("API.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 5, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5020), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://i.pinimg.com/originals/46/8c/0a/468c0abf669104e862355303efc1b6e7.png",
                            Name = "Corner Sofas",
                            Slug = "corner-sofas"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 12, 14, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5050), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://images.dfs.co.uk/i/dfs/mya_3a_simplywoollook_steelgrey_view1?$dfs_v2_pdp_m$&fmt=auto",
                            Name = "3 Seater Sofas",
                            Slug = "3-seater-sofas"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 7, 17, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5070), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://www.lapalma.it/uploads/product/thumbnail/135/collection_webp_plus_classic_trasparente.png.webp",
                            Name = "Modular Sofas",
                            Slug = "modular-sofas"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 10, 25, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5080), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://www.lecreuset.co.uk/dw/image/v2/BDSR_PRD/on/demandware.static/-/Sites-master-catalog-LC/default/dwda0e17d9/images/hires/Full_HD_PNG/LC_20190624_ZS_PS_FS_51804000010002_001.png?sw=765&sh=575&sm=fit",
                            Name = "Cookware",
                            Slug = "cookware"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 5, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5090), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0526/4261/1399/products/1.png?v=1628686245",
                            Name = "Kitchen Accessories",
                            Slug = "kitchen-accessories"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 12, 14, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5110), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "http://cdn.ecommercedns.uk/files/4/228904/0/13183260/9120001338-0.png",
                            Name = "Tableware",
                            Slug = "tableware"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 7, 17, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5120), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://www.bedsofparadise.co.uk/a-bespoke-client-folders/paradise/bespoke-images/product/carnival-double-bed-frame-3727",
                            Name = "Double Beds",
                            Slug = "double-beds"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 10, 25, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5140), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://www.afs-admin.co.uk/images-product/rialto-light-grey-linen-bed-90cm-78246",
                            Name = "Single Beds",
                            Slug = "single-beds"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 25, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5150), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://www.bedsofparadise.co.uk/a-bespoke-client-folders/paradise/bespoke-images/product/Bern%20Frame%20Grey.png",
                            Name = "King Size Beds",
                            Slug = "king-size-beds"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 1, 3, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5160), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0251/5529/products/206100313_01copy_360x.png?v=1623766088",
                            Name = "Floor Lamps",
                            Slug = "floor-lamps"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 12, 24, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5180), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://res.cloudinary.com/clippings/image/upload/t_small_square/dpr_auto,f_auto,w_auto/v2/products/brooklyn-wall-light-with-tube-glass-brass-holder-brass-ring-tube-glass-industville-clippings-11324159.png",
                            Name = "Wall Lights",
                            Slug = "wall-lights"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 11, 24, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5190), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0342/2425/products/UMAGE_packshot_2329_AsteriaUp_pearlwhite__3_4df81b09-4b79-4bdb-892b-7c5121e4c6fd_600x.png?v=1636450893",
                            Name = "Ceiling Lights",
                            Slug = "ceiling-lights"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 4, 28, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5220), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://northdecoshop.com/5910-large_default/office-chair-low-leather.jpg",
                            Name = "Office Chairs",
                            Slug = "office-chairs"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 5, 28, 18, 2, 37, 174, DateTimeKind.Unspecified).AddTicks(5230), new TimeSpan(0, 1, 0, 0, 0)),
                            ImageUrl = "https://cdn11.bigcommerce.com/s-a9q2mnae4u/images/stencil/1280x1280/products/987/1466/91e9720027c98bffd301fe0e816dc3e16f774a68__69715.1646422397.png?c=1&imbypass=on",
                            Name = "Office Desks",
                            Slug = "office-desks"
                        });
                });

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.HasOne("API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("API.Entities.ProductType", b =>
                {
                    b.HasOne("API.Entities.Category", "Category")
                        .WithMany("ProductTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Navigation("ProductTypes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("API.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
